spring:
  datasource:
    url: jdbc:mysql://localhost:3306/psm
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.zzl.person
      filters: stat,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat:
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true

mybatis-plus:
  global-config:
    db-config:
      update-strategy: IGNORED